/*
 * Semi autogenerated with: https://mholt.github.io/json-to-go/
 */

package main

// FrabEvent event struct from Frab
type FrabEvent struct {
	URL              string            `json:"url"`
	ID               int               `json:"id"`
	GUID             string            `json:"guid"`
	Logo             string            `json:"logo"`
	Date             string            `json:"date"`
	Start            string            `json:"start"`
	Duration         string            `json:"duration"`
	Room             string            `json:"room"`
	Slug             string            `json:"slug"`
	Title            string            `json:"title"`
	Subtitle         string            `json:"subtitle"`
	Track            string            `json:"track"`
	Type             string            `json:"type"`
	Language         string            `json:"language"`
	Abstract         string            `json:"abstract"`
	Description      string            `json:"description"`
	RecordingLicense string            `json:"recording_license"`
	DoNotRecord      bool              `json:"do_not_record"`
	Persons          []FrabPerson      `json:"persons"`
	Links            []FrabLinks       `json:"links"`
	Attachments      []FrabAttachments `json:"attachments"`
}

// FrabPerson person struct from FrabEvent
type FrabPerson struct {
	ID         int    `json:"id"`
	PublicName string `json:"public_name"`
}

// FrabLinks link struct from FrabEvent
type FrabLinks struct {
	URL   string `json:"url"`
	Title string `json:"title"`
}

// FrabAttachments attachment struct from FrabEvent
type FrabAttachments struct {
	URL   string `json:"url"`
	Title string `json:"title"`
}

// FrabDay day struct from Frab
type FrabDay struct {
	Index    int                    `json:"index"`
	Date     string                 `json:"date"`
	DayStart string                 `json:"day_start"`
	DayEnd   string                 `json:"day_end"`
	Rooms    map[string][]FrabEvent `json:"rooms"`
}

// FrabConference conference struct from FrabSchedule
type FrabConference struct {
	Acronym          string    `json:"acronym"`
	Title            string    `json:"title"`
	Start            string    `json:"start"`
	End              string    `json:"end"`
	DaysCount        int       `json:"daysCount"`
	TimeslotDuration string    `json:"timeslot_duration"`
	Days             []FrabDay `json:"days"`
}

// FrabSchedule struct from Frab
type FrabSchedule struct {
	Schedule struct {
		BaseURL    string         `json:"base_url"`
		Conference FrabConference `json:"conference"`
	} `json:"schedule"`
}

// FrabSpeaker struct from FrabScheduleSpeakers
type FrabSpeaker struct {
	ID             int         `json:"id"`
	Image          string      `json:"image"`
	FullPublicName string      `json:"full_public_name"`
	PublicName     string      `json:"public_name"`
	Abstract       string      `json:"abstract"`
	Description    string      `json:"description"`
	Links          []FrabLinks `json:"links"`
	Events         []FrabEvent `json:"events"`
}

// FrabScheduleSpeakers from Frab
type FrabScheduleSpeakers struct {
	ScheduleSpeakers struct {
		Speakers []FrabSpeaker `json:"speakers"`
	} `json:"schedule_speakers"`
}
